# Generated by Django 4.2.6 on 2023-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
