# Generated by Django 4.2.6 on 2023-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixify', '0002_song_album_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
