# Generated by Django 4.2.6 on 2023-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifybackend',
            name='state',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
