# Generated by Django 4.2.6 on 2023-10-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_backend', '0002_spotifybackend_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifybackend',
            name='state',
        ),
    ]
